### ISSUE TITLE
Way to allow multiple rules to match

### ISSUE THREAD

**Issue by dbarnett** [ranmocy/gmail-automata#1]
The matcher stops on the first rule that matches, but sometimes it's useful to have multiple sets of rules match independently, for instance one to add a label and one to send to inbox/archive. Is there a way to do that now? Would it be worth exploring ways to do that if not?

**Comment by LeeroyDing** [comment]
I've reviewed the comments and the proposed solution. The initial idea of using rule priorities was a good start, but the discussion evolved to a more flexible solution with an `action_after_match` enum. This enum would control the flow of rule processing, allowing for `DONE`, `NEXT_STAGE`, and `SAME_STAGE` actions.

However, I see a potential problem with the `SAME_STAGE` behavior. As pointed out in the comments, it's not entirely clear what should happen when the last rule in a stage is reached. Does it stop processing altogether, or should there be a way to continue to the next stage?

Here's my analysis and a proposed solution:

### Challenge to the Plan

The `action_after_match` enum is a good idea, but it needs to be more explicit about the flow control. The current proposal is a bit ambiguous and could lead to unexpected behavior.

### Deeper Thinking and Potential Problems

1.  **Ambiguous `SAME_STAGE` behavior:** The current `SAME_STAGE` action is overloaded. It means both "continue to the next rule in this stage" and "stop processing after this stage." This can be confusing and lead to errors.
2.  **Lack of a "continue to next stage" option:** There's no way to explicitly say "finish this stage and then move to the next one." This is a common use case, and the current proposal makes it difficult to implement.
3.  **First-wins vs. last-wins:** The comments mention that the current implementation is "first-wins," but "last-wins" would be more intuitive. This should be clarified and implemented consistently.

### Proposed Solution

I propose a revised `action_after_match` enum with the following values:

*   `CONTINUE_SAME_STAGE`: Continue to the next rule in the current stage. If this is the last rule in the stage, stop processing.
*   `CONTINUE_NEXT_STAGE`: Stop processing the current stage and move to the next one.
*   `FINISH_SAME_STAGE`: Continue to the next rule in the current stage. If this is the last rule in the stage, move to the next stage.
*   `DONE`: Stop processing all rules.

This revised enum is more explicit and addresses the issues I've identified. It also allows for more flexible and powerful rule processing.
