### ISSUE TITLE
Feature Request: Case-insensitive Regex Matches

### ISSUE THREAD

**Issue by joech4n** [ranmocy/gmail-automata#41]
It doesn't look like case-insensitive regex matches are currently supported. Could this be added?

**Comment by aaronj1335** [comment]
Is this not covered by #30 ?

**Comment by joech4n** [comment]
Ah, looks like it is covered by it. Thanks!

**Comment by joech4n** [comment]
But it looks like the main spreadsheet has not been updated, which is why i was not seeing the feature.

**Comment by ranmocy** [comment]
Even I update the master spreadsheet, you will need to re-ford it and copy your configs over.
I would suggest you to deploy the latest code directly to your current spreadsheet.
See https://github.com/ranmocy/gmail-automata#deploy

**Comment by aaronj1335** [comment]
When you copy the spreadsheet it also makes a copy of the script. If you would like a new deployment of the script, you can clone this repo run ‘non install’, and then ‘npx deploy’.

**Comment by joech4n** [comment]
Thanks! Updating via `npx deploy` worked.
