### ISSUE TITLE
Error - `Message: Invalid regular expression: /?!.*domain.com/: Nothing to repeat`

### ISSUE THREAD

**Issue by joech4n** [ranmocy/gmail-automata#43]
Error:
```
Message: Invalid regular expression: /?!.*domain.com/: Nothing to repeat
```

Rule:

```
(and
    (from /?!.*domain.com/)
    (or
        (body /.*string1/i)
        (body /.*string2/i)))
```

It looks like some issue with the regex parsing. Is negative lookahead not properly supported or am I doing something wrong here?

Thanks for any help!

**Comment by aaronj1335** [comment]
Negative look-aheads in JS need parens, so `/(?!.*domain.com)/` should work.

**Comment by aaronj1335** [comment]
Also note that you can try these out either in your browser's dev tools, or by adding a test case in https://github.com/ranmocy/gmail-automata/blob/d582b2a22e540f511f06f26c429013ab61776f21/Condition.ts#L241 and running `npm test`.

**Comment by joech4n** [comment]
Thanks, https://github.com/ranmocy/gmail-automata/issues/43#issuecomment-725023795 did it!
