### ISSUE TITLE
Emails not being processed - task stops processing?

### ISSUE THREAD

**Issue by nroach** [ranmocy/gmail-automata#50]
I'm running into an issue where emails are processed if I manually mark them as `0unprocessed` but new arrivals are not.  I see dropouts in my stats log like this:

`| num_invocations | total_threads | min_threads | max_threads | avg_threads | total_messages
-- | -- | -- | -- | -- | -- | --
05/26/2021 | 108 | 103 | 0 | 50 | 0.95 | 103
05/27/2021 | 290 | 23 | 0 | 7 | 0.08 | 23
05/28/2021 | 295 | 22 | 0 | 6 | 0.07 | 22
05/29/2021 | 288 | 0 | 0 | 0 | 0.00 | 0
05/30/2021 | 288 | 0 | 0 | 0 | 0.00 | 0
05/31/2021 | 289 | 0 | 0 | 0 | 0.00 | 0
06/01/2021 | 288 | 0 | 0 | 0 | 0.00 | 0
06/02/2021 | 287 | 95 | 0 | 50 | 0.33 | 95

I've tried restarting the script from the Gmail Automata menu in the sheet, and that works for a while but doesn't seem to last more than a day or two.

Separately, I also have a bunch of emails that arrived on 6/2/2021 (and that date shows with processing activity above) but they aren't marked as 0unprocessed or 0processed.  But again, if I manually mark them it seems to cover it on next run.

_where do i look to start troubleshooting this?_. I'm not getting error reports or seeing messages marked as 0error, so it's a silent fail as far as I can tell.  Is there a way to see if this is coming from the Script or from the initial rules in Gmail?

**Comment by nroach** [comment]
I see invocations on each day, which seems to me the task is at least starting, but not sure why total_threads  and total_messages is 0.

**Comment by ranmocy** [comment]
If by manually adding emails to 0unprocessed works, it means the script works fine.
Adding new emails with the label is not done by the script, but the standard Gmail filter.
See the [setup doc](https://github.com/ranmocy/gmail-automata/blob/master/README.md#setup) step 7.
